services:
  server:
    container_name: receiver_fastapi
    build:
      context: .
    ports:
      - 8000:8000
    command: "uvicorn src.main:app --reload --host=0.0.0.0"
    develop:
      watch:
        - action: rebuild
          path: .
    volumes:
      - .:/app
    env_file:
      - .env
